namespace Application.DTOs;

public class EmployeeDto
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmployeeTypeName { get; set; }
    public decimal TotalHours { get; set; }
    public string VerifiedLogo { get; set; }
    public string NotVerifiedLogo { get; set; }
    public string MaritalStatus { get; set; }
    public string CountryCode { get; set; }
    public string PhoneNumber { get; set; }
    public string Email { get; set; }
    public byte EmployementTypeId { get; set; }
    public byte EmployeeTypeId { get; set; }
    public string PinCode { get; set; }
    public string UTRNumber { get; set; }
    public byte UTRNumberStatus { get; set; }
    public string ProfileImageUrl { get; set; }
    public string BiometricResidenceCardUrl { get; set; }
    public byte BiometricResidenceCardStatus { get; set; }
    public string BiometricResidenceCardRejectionReason { get; set; }
    public string PassportUrl { get; set; }
    public byte PassportStatus { get; set; }
    public string PassportRejectionReason { get; set; }
    public byte DbsNumberStatus { get; set; }
    public string DbsNumberRejectionReason { get; set; }
    public byte DbsCertificateStatus { get; set; }
    public string DbsCertificateRejectionReason { get; set; }
    public string P45DocumentUrl { get; set; }
    public string UTRNumberRejectionReason { get; set; }
    public string? CVFileURL { get; set; }
    public string? Address { get; set; }
    public string? Address2 { get; set; }
    public string? City { get; set; }
    public string? Country { get; set; }
    public bool IsActive { get; set; }
    public bool IsDeleted { get; set; }
    public byte AccountStatus { get; set; }
    public string AccountStatusChangeReason { get; set; }
    public double Latitude { get; set; }
    public double Longitude { get; set; }
    public string? ProofOfExemptionUrl { get; set; }
    public string? VaccinationCertificateUrl { get; set; }
    public byte? NoOfShifts { get; set; }
    public DateTime? DateOfQualification { get; set; }
    public byte? NurseTypeId { get; set; }
    public string NMCPin { get; set; }
    public byte NMCPinStatus { get; set; }
    public string NMCPinRejectionReason { get; set; }
    public string NationalInsuranceNumber { get; set; }
    public byte NationalInsuranceNumberStatus { get; set; }
    public string NationalInsuranceNumberRejectionReason { get; set; }
    public byte? YearsOfExperience { get; set; }
    public bool? HaveQualification { get; set; }
    public bool? IsSubjectOfInvestigation { get; set; }
    public string? WorkGapReason { get; set; }
    public string? PersonalLink { get; set; }
    public string? ProfessionalLink { get; set; }
    public Guid EmployeeSecretId { get; set; }
    public string LinkSharedOnEmails { get; set; }
    public string DbsCertificateUrl { get; set; }
    public DateTime? DbsExpiryDate { get; set; }
    public string DbsNumber { get; set; }
    public bool HaveDbsNumber { get; set; }
    public string AccountName { get; set; }
    public string AccountNumber { get; set; }
    public string SortCode { get; set; }
    public string BankName { get; set; }
    public DateTime DateOfBirth { get; set; }
    public byte Gender { get; set; }
    public string Nationality { get; set; }
    public bool Policy1 { get; set; }
    public bool Policy2 { get; set; }
    public bool Policy3 { get; set; }
    public bool Policy4 { get; set; }
    public byte InterviewStatus { get; set; }
    public string InterviewRemarks { get; set; }
    public string InterviewFileUrl { get; set; }
    public string CompanyNumber { get; set; }
    public byte CompanyNumberStatus { get; set; }
    public string CompanyNumberRejectionReason { get; set; }
    public string AccessNIUrl { get; set; }
    public DateTime? AccessNIExpiryDate { get; set; }
    public byte AccessNIStatus { get; set; }
    public string AccessNIRejectionReason { get; set; }
    public string NationalInsuranceUrl { get; set; }
    public byte NationalInsuranceStatus { get; set; }
    public string NationalInsuranceRejectionReason { get; set; }
    public List<Reference> PersonalReference { get; set; }
    public List<Reference> ProfessionalReference { get; set; }
    public List<Employement> Employements { get; set; }
}
